export const postData = [
  {
    id: 1,
    title: "real time photo generation",
    tag: "cartoons combined",
    remixid: "cartoons-combined",
    type: "dynamic",
    username: "iyushjain",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285179/feed/explore/ehiuac703b5hxkpiggik.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285179/feed/explore/ehiuac703b5hxkpiggik.png",
  },
  {
    id: 2,
    title: "real time photo generation",
    tag: "fututre of work",
    remixid: "fututre-of-work",
    type: "dynamic",
    username: "iyushjain",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285178/feed/explore/dvqjntoppsntslkshwhh.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285178/feed/explore/dvqjntoppsntslkshwhh.png",
  },
  {
    id: 3,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "iyushjain",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285178/feed/explore/gwkultyyp4ueuppxqtny.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285178/feed/explore/gwkultyyp4ueuppxqtny.png",
  },
  {
    id: 4,
    title: "real time photo generation",
    tag: "super heroes combined",
    remixid: "super-heroes-combined",
    type: "dynamic",
    username: "mogumogu",
    avatar: "https://picsum.photos/id/99/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285180/feed/explore/p2htcctjthgm2rcxluep.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285180/feed/explore/p2htcctjthgm2rcxluep.png",
  },
  {
    id: 5,
    title: "real time photo generation",
    tag: "super heroes combined",
    remixid: "super-heroes-combined",
    type: "dynamic",
    username: "mogumogu",
    avatar: "https://picsum.photos/id/99/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285180/feed/explore/l8rovwmn1ytxf6klfefn.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285180/feed/explore/l8rovwmn1ytxf6klfefn.png",
  },
  {
    id: 6,
    title: "real time photo generation",
    tag: "super heroes combined",
    remixid: "super-heroes-combined",
    type: "dynamic",
    username: "churo09",
    avatar: "https://picsum.photos/id/102/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285178/feed/explore/kdxybiaxdlhey1ak56hx.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285178/feed/explore/kdxybiaxdlhey1ak56hx.png",
  },
  {
    id: 7,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "yushiyushi",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285179/feed/explore/zlwmelrfwyddwmapzl9i.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285179/feed/explore/zlwmelrfwyddwmapzl9i.png",
  },
  {
    id: 8,
    title: "real time photo generation",
    tag: "future of work",
    remixid: "future-of-work",
    type: "dynamic",
    username: "yushiyushi",
    avatar: "https://picsum.photos/id/10/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285179/feed/explore/loqurcidlslbwl6oodau.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285179/feed/explore/loqurcidlslbwl6oodau.png",
  },
  {
    id: 9,
    title: "real time photo generation",
    tag: "future of work",
    remixid: "future-of-work",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285177/feed/explore/gnygoy8kmzseeo1txaix.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285177/feed/explore/gnygoy8kmzseeo1txaix.png",
  },
  {
    id: 10,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285177/feed/explore/dlymtsyggboeqrtp57uv.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285177/feed/explore/dlymtsyggboeqrtp57uv.png",
  },
  {
    id: 11,
    title: "real time photo generation",
    tag: "future of work",
    remixid: "future-of-work",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285180/feed/explore/dmmeyvmwtfmbkycnplek.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285180/feed/explore/dmmeyvmwtfmbkycnplek.png",
  },
  {
    id: 12,
    title: "real time photo generation",
    tag: "future of work",
    remixid: "future-of-work",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285180/feed/explore/jn80ehtqnpzecybqzzfa.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285180/feed/explore/jn80ehtqnpzecybqzzfa.png",
  },
  {
    id: 13,
    title: "real time photo generation",
    tag: "future of work",
    remixid: "future-of-work",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285179/feed/explore/ymjeaancvj1yhwh6wnnm.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285179/feed/explore/ymjeaancvj1yhwh6wnnm.png",
  },
  {
    id: 14,
    title: "scribble your mind",
    tag: "words keep changing",
    remixid: "words-keep-changing",
    type: "scribble",
    username: "iyushjain",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285174/feed/explore/z4hsti4tplciieov9aqs.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285174/feed/explore/z4hsti4tplciieov9aqs.png",
  },
  {
    id: 15,
    title: "scribble your mind",
    tag: "words keep changing",
    remixid: "words-keep-changing",
    type: "scribble",
    username: "iyushjain",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285174/feed/explore/z4hsti4tplciieov9aqs.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285174/feed/explore/z4hsti4tplciieov9aqs.png",
  },
  {
    id: 16,
    title: "scribble your mind",
    tag: "words keep changing",
    remixid: "words-keep-changing",
    type: "scribble",
    username: "iyushjain",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285175/feed/explore/cvtss9iwdefhm22jp85v.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285175/feed/explore/cvtss9iwdefhm22jp85v.png",
  },
  {
    id: 17,
    title: "scribble your mind",
    tag: "words keep changing",
    remixid: "words-keep-changing",
    type: "scribble",
    username: "iyushjain",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285177/feed/explore/zxn0eww6ccehl6uj78qq.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285177/feed/explore/zxn0eww6ccehl6uj78qq.png",
  },
  {
    id: 18,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/d77krrethkx11tl2vynj.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/d77krrethkx11tl2vynj.png",
  },
  {
    id: 19,
    title: "scribble your mind",
    tag: "words keep changing",
    remixid: "words-keep-changing",
    type: "scribble",
    username: "iyushjain",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285174/feed/explore/v1qelnusnqpsy0m1gpfj.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285174/feed/explore/v1qelnusnqpsy0m1gpfj.png",
  },
  {
    id: 20,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285177/feed/explore/cdv5qb0zzof0qfjy5ysw.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285177/feed/explore/cdv5qb0zzof0qfjy5ysw.png",
  },
  {
    id: 21,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/okopi91todzwmczern2o.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/okopi91todzwmczern2o.png",
  },
  {
    id: 22,
    title: "real time photo generation",
    tag: "appocalypse now",
    remixid: "appocalypse-now",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/lkdqanikhkoqvzwpqrxh.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/lkdqanikhkoqvzwpqrxh.png",
  },
  {
    id: 22,
    title: "text to tunes",
    tag: "90s Jazz",
    remixid: "90s-jazz",
    type: "audio",
    username: "yushiyushi",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://replicate.delivery/pbxt/SCiO1SBkqj7gL5cTsq8AXz5pIwPajeiWbb9s17KtyQ2G3OFIA/gen_sound.wav",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289215/feed/explore/hyoauun11sa5mxtpfaks.png",
  },
  {
    id: 23,
    title: "text to tunes",
    tag: "90s Jazz",
    remixid: "90s-jazz",
    type: "audio",
    username: "yushiyushi",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://replicate.delivery/pbxt/SCiO1SBkqj7gL5cTsq8AXz5pIwPajeiWbb9s17KtyQ2G3OFIA/gen_sound.wav",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289215/feed/explore/ujotajkix8qjqqftuh2r.png",
  },
  {
    id: 24,
    title: "text to tunes",
    tag: "90s Jazz",
    remixid: "90s-jazz",
    type: "audio",
    username: "yushiyushi",
    avatar: "https://picsum.photos/id/91/200",
    src: "https://replicate.delivery/pbxt/SCiO1SBkqj7gL5cTsq8AXz5pIwPajeiWbb9s17KtyQ2G3OFIA/gen_sound.wav",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289215/feed/explore/evpr8h4qqphtl8tnhmbo.png",
  },
  {
    id: 25,
    title: "real time photo generation",
    tag: "appocalypse now",
    remixid: "appocalypse-now",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/tnpux8vumljcdboyllht.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/tnpux8vumljcdboyllht.png",
  },
  {
    id: 26,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289732/feed/explore/v7ufe6tlcgxu2ix2rqe9.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289732/feed/explore/v7ufe6tlcgxu2ix2rqe9.png",
  },
  {
    id: 27,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289732/feed/explore/c40dcl3hsrxlrjuqfufq.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289732/feed/explore/c40dcl3hsrxlrjuqfufq.png",
  },
  {
    id: 28,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289732/feed/explore/sdhcfmlbu6npm83tjs7v.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289732/feed/explore/sdhcfmlbu6npm83tjs7v.png",
  },
  {
    id: 29,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289723/feed/explore/cgkm7havxmyyx7cajtzo.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708289723/feed/explore/cgkm7havxmyyx7cajtzo.png",
  },
  {
    id: 30,
    title: "real time photo generation",
    tag: "weird food",
    remixid: "weird-food",
    type: "dynamic",
    username: "issuepissue",
    avatar: "https://picsum.photos/id/110/200",
    src: "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/d77krrethkx11tl2vynj.png",
    thumbnail:
      "https://res.cloudinary.com/dwwcarx9g/image/upload/v1708285176/feed/explore/d77krrethkx11tl2vynj.png",
  },
];
